"""Regenerate fonts.css: Apfel Grotezk (SIL OFL) embedded as data URIs so it loads anywhere,
including artifacts, whose CSP blocks font files from other hosts. Paid faces (Polyamine, Restora)
are not embedded: they are unlicensed, so they show only where installed (see ../type.md)."""
import base64, pathlib
here = pathlib.Path(__file__).parent
faces = [("ApfelGrotezk-Regular.otf", 400), ("ApfelGrotezk-Mittel.otf", 500), ("ApfelGrotezk-Fett.otf", 700)]
out = ["/* Generated by build-fonts.py; do not edit by hand. */"]
for f, w in faces:
    b = base64.b64encode((here / "fonts" / f).read_bytes()).decode()
    out.append('@font-face{font-family:"Apfel Grotezk";font-weight:%d;font-display:swap;src:url(data:font/otf;base64,%s) format("opentype")}' % (w, b))
out.append('@font-face{font-family:"Polyamine";src:local("Polyamine"),local("Polyamine-Regular"),local("Polyamine Regular");font-display:swap}')
out.append('@font-face{font-family:"Restora";src:local("Restora"),local("Restora-Regular"),local("Restora Regular");font-display:swap}')
(here / "fonts.css").write_text("\n".join(out) + "\n")
