"""Build ../woodcuts.html: every woodcut in system/woodcuts/, inlined so it takes the ground's ink
(currentColor), on a switchable ground. Descriptions come from the table in woodcuts/README.md."""
import pathlib, re, html

here = pathlib.Path(__file__).parent
wc = here / "woodcuts"
readme = (wc / "README.md").read_text()
desc = dict(re.findall(r"^\| `([\w-]+)\.svg` \| (.+?) \|$", readme, re.M))

GROUPS = [
    ("Swallows", "swallow"), ("Mountains", "mountain"), ("Leaves", "leaf"), ("Wind", "wind"),
    ("Fruit", "fruit"), ("People", "circle"), ("Seeds", "seeds"),
]
STRONG = {"mountain-peak", "leaf-single", "leaf-ginkgo", "leaf-sprig", "fruit-apple", "fruit-pear",
          "fruit-pomegranate", "fruit-cherries", "swallow-bold", "circle-of-chairs-above"}
WEAK = {"swallow-perched": "reads more like a generic songbird", "swallow-above": "still a little moth-like"}

def inline(name):
    s = (wc / f"{name}.svg").read_text().strip()
    s = re.sub(r'\s(width|height)="[^"]*"', "", s, count=2)          # let CSS size it
    s = s.replace('style="color:#1b1916"', 'class="woodcut"', 1)     # follow the ground's ink
    s = s.replace("<svg ", f'<svg role="img" aria-label="{html.escape(desc.get(name, name))}" ', 1)
    return s

sections, n = [], 0
for title, prefix in GROUPS:
    names = sorted(p.stem for p in wc.glob(f"{prefix}*.svg"))
    if prefix == "seeds":
        names = ["seeds", "seeds-red"]
    plates = []
    for name in names:
        n += 1
        status = ' <span class="wc-tag">strong</span>' if name in STRONG else (f' <span class="wc-tag wc-weak">weak: {WEAK[name]}</span>' if name in WEAK else "")
        wide = " wc-wide" if prefix == "seeds" else ""
        plates.append(f'''    <figure class="wc-plate{wide}">
      <div class="wc-art">{inline(name)}</div>
      <figcaption><span class="fig-no">Plate {n}</span>{html.escape(desc.get(name, ""))}{status}<br><code>system/woodcuts/{name}.svg</code></figcaption>
    </figure>''')
    sections.append(f'''  <section class="wc-group"><h2 class="label">{title}</h2>
  <div class="wc-grid">
{chr(10).join(plates)}
  </div></section>''')

page = f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>Seeds of Renaissance · Woodcuts</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,300..700&family=Hanken+Grotesk:wght@400;500;700&family=Fraunces:ital,opsz,wght,SOFT@0,9..144,300..500,100;1,9..144,300..500,100&display=swap">
<link rel="stylesheet" href="system/fonts.css">
<link rel="stylesheet" href="system/tokens.css">
<link rel="stylesheet" href="system/components.css">
<style>
/* GENERATED by system/build-woodcuts.py from system/woodcuts/*.svg — do not edit by hand. */
html, body {{ margin: 0; background: var(--paper) }}
.wc-head {{ padding-block: clamp(40px, 6cqi, 80px) 24px; display: grid; gap: 14px; max-width: 900px }}
.wc-head h1 {{ font-family: var(--font-display); font-size: var(--t-title); line-height: .98 }}
.wc-head p {{ font-size: var(--t-intro); max-width: 52ch }}
.wc-head ul {{ margin: 0; padding-left: 20px; display: grid; gap: 4px; font-size: var(--t-small); color: var(--muted); max-width: 70ch }}
.wc-tools {{ position: sticky; top: env(safe-area-inset-top, 0px); z-index: 20; background: var(--paper); border-block: 1px solid var(--rule); display: flex; flex-wrap: wrap; gap: 8px 16px; align-items: center; padding-block: 10px }}
.wc-tools button {{ font-family: var(--font-label); font-size: var(--t-label); font-weight: 500; letter-spacing: .12em; text-transform: uppercase; padding: 8px 14px; border: 1px solid var(--ink); background: transparent; color: var(--ink); cursor: pointer }}
.wc-tools button[aria-pressed="true"] {{ background: var(--ink); color: var(--paper) }}
.wc-group {{ padding-block: 32px 8px }}
.wc-group > h2 {{ color: var(--muted); margin-bottom: 14px; display: block }}
.wc-grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(min(260px, 100%), 1fr)); gap: var(--gap-m) }}
.wc-plate {{ display: grid; gap: 10px; align-content: start }}
.wc-wide {{ grid-column: span 2 }}
.wc-art {{ aspect-ratio: 4 / 3; display: grid; place-items: center; padding: 22px; border: 1px solid var(--rule); background: var(--ground, var(--white)) }}
.wc-wide .wc-art {{ aspect-ratio: 16 / 9 }}
.wc-art svg {{ width: 100%; height: 100%; color: var(--wc-ink, var(--ink)) }}
.wc-plate figcaption code {{ font-size: 12px; color: var(--muted); font-style: normal }}
.wc-tag {{ font-family: var(--font-label); font-style: normal; font-size: var(--t-meta); letter-spacing: .1em; text-transform: uppercase; color: var(--ink); border: 1px solid var(--rule); padding: 1px 6px; margin-left: 6px }}
.wc-weak {{ color: var(--muted) }}
body[data-ground="white"] {{ --ground: var(--white) }}
body[data-ground="paper"] {{ --ground: var(--paper) }}
body[data-ground="sun"] {{ --ground: var(--sunlight) }}
body[data-ground="night"] {{ --ground: var(--night); --wc-ink: var(--chalk) }}
body[data-ground="night"] .wc-art {{ border-color: var(--night) }}
@container (max-width: 600px) {{ .wc-wide {{ grid-column: auto }} }}
</style>
</head>
<body class="sor gutter" data-ground="white" style="padding-bottom:64px">
<header class="wc-head">
  <span class="label muted">Seeds of Renaissance · Design system · Graphics</span>
  <h1>Woodcuts</h1>
  <p>The full set of woodcut graphics: a black shape, white carved lines and a slightly rough printed edge. {n} plates.</p>
  <ul>
    <li>Every file is an SVG with a transparent background. Its ink follows the page's text colour, so it prints ink on light grounds and chalk on night.</li>
    <li>The carved lines are real cut-outs: the ground shows through them, as in a print.</li>
    <li>The swallow, seal, seeds and clusters are also in the page sprite (<code>graphics.js</code>) for use with <code>&lt;use href="#…"&gt;</code>. See <a class="link" href="graphics.md">graphics.md</a> for the rules.</li>
    <li>First drafts, drawn in code (<code>system/woodcuts/wc.py</code>). Open: redraw by hand, or base on public-domain prints.</li>
  </ul>
</header>
<div class="wc-tools" role="group" aria-label="Ground">
  <span class="label muted">Ground</span>
  <button type="button" data-g="white" aria-pressed="true">White</button>
  <button type="button" data-g="paper" aria-pressed="false">Paper</button>
  <button type="button" data-g="sun" aria-pressed="false">Sunlight</button>
  <button type="button" data-g="night" aria-pressed="false">Night</button>
</div>
{chr(10).join(sections)}
<script>
document.querySelectorAll('.wc-tools button').forEach(function (b, _, all) {{
  b.addEventListener('click', function () {{
    document.body.dataset.ground = b.dataset.g;
    all.forEach(function (x) {{ x.setAttribute('aria-pressed', x === b ? 'true' : 'false') }});
  }});
}});
</script>
</body>
</html>
'''
(here.parent / "woodcuts.html").write_text(page)
print(f"woodcuts.html: {n} plates")
